# Generated by Django 4.1.7 on 2023-05-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0003_rename_productos_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default=True, max_length=7, primary_key=True, serialize=False),
        ),
    ]
