# Generated by Django 4.1.7 on 2023-05-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0005_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='RP', max_length=7, primary_key=True, serialize=False),
        ),
    ]
